### ISSUE TITLE
TraceBars fails if the trace file already exists

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/KCWI_DRP#11]
```2020-05-12 07:42:06:DRPF:ERROR: Exception while invoking TraceBars
Traceback (most recent call last):
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/core/framework.py", line 209, in execute
    action_output = pipeline.get_action(action_name)(action, context)
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/pipelines/base_pipeline.py", line 84, in f
    return obj.apply()
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/primitives/base_primitive.py", line 57, in apply
    self.output = self._perform()
  File "/Users/lrizzi/PythonProjects/KCWI_DRP/kcwidrp/primitives/TraceBars.py", line 148, in _perform
    "Cont. bars image")})
  File "/Users/lrizzi/PythonProjects/KCWI_DRP/kcwidrp/primitives/kcwi_file_primitives.py", line 602, in write_table
    t.write(output_file, format='fits')
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/table/connect.py", line 113, in __call__
    registry.write(instance, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/io/registry.py", line 566, in write
    writer(data, *args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/astropy/io/fits/connect.py", line 411, in write_table_fits
    raise OSError(f"File exists: {output}")
OSError: File exists: redux/kb200221_00021_trace.fits
2020-05-12 07:42:06:DRPF:INFO: Event failed: name contbar_trace_bars, action TraceBars, arg name kb200221_00021.fits, recurr False
```

**Comment by lucarizzi** [comment]
We have a choice: should we automatically overwrite an existing trace file or should we catch this error and move on?
