### ISSUE TITLE
Error in Flux Calibrate

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/KCWI_DRP#14]
```2020-05-16 10:22:14:KCWI:INFO: Not found in data/stds: /Users/lrizzi/PythonProjects/KCWI_DRP/kcwidrp/data/stds/fiege92.fits
2020-05-16 10:22:14:DRPF:INFO: Event failed: name object_make_invsens, action MakeInvsens, arg name kb200516_00057.fits, recurr False
2020-05-16 10:22:14:KCWI:INFO: Checking precondition for FluxCalibrate
2020-05-16 10:22:14:DRPF:ERROR: Exception while invoking FluxCalibrate
Traceback (most recent call last):
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/core/framework.py", line 209, in execute
    action_output = pipeline.get_action(action_name)(action, context)
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/pipelines/base_pipeline.py", line 84, in f
    return obj.apply()
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/primitives/base_primitive.py", line 56, in apply
    if self._pre_condition():
  File "/Users/lrizzi/PythonProjects/KCWI_DRP/kcwidrp/primitives/FluxCalibrate.py", line 26, in _pre_condition
    tab = self.context.proctab.n_proctab(frame=self.action.args.ccddata,
AttributeError: 'Arguments' object has no attribute 'ccddata'
2020-05-16 10:22:14:DRPF:INFO: Event failed: name object_flux_calibrate, action FluxCalibrate, arg name undef, recurr False```

**Comment by lucarizzi** [comment]
The problem is that you cannot call FluxCalibrate if MakeInvsens fails

**Comment by lucarizzi** [comment]
I think this problem is related to the framework and not to the pipeline, ignore for the moment, will discuss with Shui.

**Comment by lucarizzi** [comment]
Fixed by a modification of the framework, waiting for the PR to be accepted.
