### ISSUE TITLE
Error in MakeMasterSky

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/KCWI_DRP#15]
```2020-05-16 10:23:05:KCWI:INFO: Checking precondition for MakeMasterSky
2020-05-16 10:23:05:DRPF:ERROR: Exception while invoking MakeMasterSky
Traceback (most recent call last):
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/core/framework.py", line 209, in execute
    action_output = pipeline.get_action(action_name)(action, context)
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/pipelines/base_pipeline.py", line 84, in f
    return obj.apply()
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/primitives/base_primitive.py", line 56, in apply
    if self._pre_condition():
  File "/Users/lrizzi/PythonProjects/KCWI_DRP/kcwidrp/primitives/MakeMasterSky.py", line 28, in _pre_condition
    suffix = self.action.args.new_type.lower()
AttributeError: 'Arguments' object has no attribute 'new_type'
2020-05-16 10:23:05:DRPF:INFO: Event failed: name object_make_sky, action MakeMasterSky, arg name undef, recurr False
```

**Comment by scizen9** [comment]
new_type is now assigned in kcwi_pipeline.py prior to calling each flat processing pipeline.
