### ISSUE TITLE
TypeError in check_cals

### ISSUE THREAD

**Issue by tansb** [Keck-DataReductionPipelines/KCWI_DRP#162]
I tried running check_cals (check_cals raw/KB*.fits) and encountered the following error:

```
Found 102 files to inspect
Traceback (most recent call last):
  File "/Users/tbarone/opt/anaconda3/envs/kcwidrp/bin/check_cals", line 8, in <module>
    sys.exit(main())
  File "/Users/tbarone/opt/anaconda3/envs/kcwidrp/lib/python3.7/site-packages/kcwidrp/scripts/check_cals.py", line 129, in main
    proctab = Proctab(dummy_logger)
TypeError: __init__() takes 1 positional argument but 2 were given
```
After editing line 129 in the check_cals.py file to remove the dummy_logger variable input to proctab the script then ran. Looks like this is related to a recent change 2ea95ea which removed the logger argument from proctab?

**Comment by MNBrod** [comment]
Yup, that looks like the issue, thanks for tracking it down! I'll issue a fix shortly
