### ISSUE TITLE
DRPF:ERROR: Exception arrays used as indices must be of integer (or boolean) type while invoking MakeMasterFlat

### ISSUE THREAD

**Issue by geoffcfchen** [Keck-DataReductionPipelines/KCWI_DRP#58]
Hi, I used the python version DRP. While reducing the data, I saw some of the files show the following error messages. Do I need to worry about it? Thanks.

**2021-05-17 06:56:56:KCWI:INFO: Using 5140 knots for bspline fit
2021-05-17 06:57:08:py.warnings:WARNING: /Users/Geoff/GitHub/KCWI_DRP/kcwidrp/core/bspline/Bspline.py:585: PydlutilsUserWarning: Bad entries: [   0 5136]
  warn('Bad entries: ' + str(negative.nonzero()[0]), PydlutilsUserWarning)
2021-05-17 06:57:08:DRPF:ERROR: Exception arrays used as indices must be of integer (or boolean) type while invoking MakeMasterFlat
Traceback (most recent call last):
  File "/Users/Geoff/anaconda3/envs/python37/lib/python3.7/site-packages/keckdrpframework-0.1.dev0-py3.7.egg/keckdrpframework/core/framework.py", line 229, in execute
    action_output = pipeline.get_action(action_name)(action, context)
  File "/Users/Geoff/anaconda3/envs/python37/lib/python3.7/site-packages/keckdrpframework-0.1.dev0-py3.7.egg/keckdrpframework/pipelines/base_pipeline.py", line 84, in f
    return obj.apply()
  File "/Users/Geoff/anaconda3/envs/python37/lib/python3.7/site-packages/keckdrpframework-0.1.dev0-py3.7.egg/keckdrpframework/primitives/base_primitive.py", line 57, in apply
    self.output = self._perform()
  File "/Users/Geoff/GitHub/KCWI_DRP/kcwidrp/primitives/MakeMasterFlat.py", line 536, in _perform
    fullbkpt=bkpt)
  File "/Users/Geoff/GitHub/KCWI_DRP/kcwidrp/core/bspline/Bspline.py", line 762, in iterfit
    x2=x2work)
  File "/Users/Geoff/GitHub/KCWI_DRP/kcwidrp/core/bspline/Bspline.py", line 202, in fit
    return self.maskpoints(errb[0]), yfit
  File "/Users/Geoff/GitHub/KCWI_DRP/kcwidrp/core/bspline/Bspline.py", line 433, in maskpoints
    hmm = err[np.unique(err/self.npoly)]/self.npoly
IndexError: arrays used as indices must be of integer (or boolean) type
2021-05-17 06:57:08:DRPF:INFO: Event failed: name flat_make_master, action MakeMasterFlat, arg name kb210516_00030.fits, recurr False**

**Comment by MNBrod** [comment]
Yes, this is a problem (the pipeline will try to continue, but will not accomplish very much, since it failed to make master flat to apply). I'll take a look and try to replicate the issue. Could you upload both of the log files to this thread (DRPF.log and KCWI.log)

**Comment by geoffcfchen** [comment]
[DRPF.log](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/files/6504508/DRPF.log)
[KCWI.log](https://github.com/Keck-DataReductionPipelines/KCWI_DRP/files/6504513/KCWI.log)


Thank you!

**Comment by geoffcfchen** [comment]
Any updates on this? Thanks.
