### ISSUE TITLE
Bug in MakeMasterFlat

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/KCWI_DRP#7]
see trace:

```2020-04-29 15:24:14:KCWI:INFO: >>> Saving to redux/kb200221_00024_sflat.fits
2020-04-29 15:24:15:DRPF:INFO: writing proc table file: kcwi.proc
2020-04-29 15:24:15:KCWI:INFO: kcwidrp.primitives.StackFlats.StackFlats
2020-04-29 15:24:15:DRPF:INFO: Event completed: name flat_make_stack, action StackFlats, arg name kb200221_00029.fits, recurr False
2020-04-29 15:24:15:KCWI:INFO: Checking precondition for MakeMasterFlat
2020-04-29 15:24:15:DRPF:INFO: Looking for MFLAT frames
2020-04-29 15:24:15:DRPF:INFO: Looking for SFLAT frames
2020-04-29 15:24:15:KCWI:INFO: pre condition got 1, expecting 1
2020-04-29 15:24:15:KCWI:INFO: Creating master illumination correction
2020-04-29 15:24:15:DRPF:INFO: Looking for ARCLAMP frames
2020-04-29 15:24:15:KCWI:INFO: Reading image: kb200221_00023_wavemap.fits
2020-04-29 15:24:15:KCWI:INFO: Reading image: kb200221_00023_slicemap.fits
2020-04-29 15:24:15:KCWI:INFO: Reading image: kb200221_00023_posmap.fits
2020-04-29 15:24:15:KCWI:INFO: Reading image: kb200221_00024_sflat.fits
2020-04-29 15:24:15:KCWI:INFO: Internal Flat
2020-04-29 15:24:23:KCWI:INFO: Wavelength limits: 3226.2 - 5796
2020-04-29 15:24:23:KCWI:INFO: Internal flats require vignetting correction
2020-04-29 15:24:23:KCWI:INFO: Using 4425.6 - 4597.0 A of slice 9
2020-04-29 15:24:43:KCWI:INFO: Applying vignetting correction...
2020-04-29 15:24:44:KCWI:INFO: Done, now handling buffer region
/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/primitives/base_primitive.py:57: RankWarning: Polyfit may be poorly conditioned
  self.output = self._perform()
2020-04-29 15:24:59:KCWI:INFO: Vignetting correction complete.
2020-04-29 15:24:59:KCWI:INFO: Fitting master illumination
2020-04-29 15:24:59:KCWI:INFO: Using 100 knots for bspline fit
2020-04-29 15:24:59:DRPF:ERROR: Exception while invoking MakeMasterFlat
Traceback (most recent call last):
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/core/framework.py", line 209, in execute
    action_output = pipeline.get_action(action_name)(action, context)
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/pipelines/base_pipeline.py", line 84, in f
    return obj.apply()
  File "/Users/lrizzi/PythonProjects/KeckDRPFramework/keckdrpframework/primitives/base_primitive.py", line 57, in apply
    self.output = self._perform()
  File "/Users/lrizzi/PythonProjects/KCWI_DRP/kcwidrp/primitives/MakeMasterFlat.py", line 453, in _perform
    sftr, _ = bspline.iterfit(xfr, yfr, fullbkpt=bkpt)
  File "/Users/lrizzi/.local/lib/python3.7/site-packages/pydl/pydlutils/bspline.py", line 618, in iterfit
    goodbk = sset.mask.nonzero()[0]
UnboundLocalError: local variable 'sset' referenced before assignment
2020-04-29 15:24:59:DRPF:INFO: Event failed: name flat_make_master, action MakeMasterFlat, arg name kb200221_00029.fits, recurr False
```

**Comment by scizen9** [comment]
This is because you do not have my version of pydl.  We need to discuss what to do with the bspline fitting routines from pydl, since it doesn't appear that we can update the public version and that version contains many bugs.

**Comment by scizen9** [comment]
Added bspline module which includes bug-corrected version of routines from pydl.
