### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'OBJECT'

### ISSUE THREAD

**Issue by McKendree** [Keck-DataReductionPipelines/KCWI_DRP#95]
I'm trying to use the python version of the KCWI DRP to reduce a set of data files from June 19th, but when I execute the command "reduce_kcwi -f KB*.fits -g" I get the following error, and no plots or reduced files are produced. All of the files to be reduced are in the format "KB*.fits" so I'm not clear why there is a warning stating that "KB*.fits is not a file".

2021-07-28 18:40:25,085 Starting Bokeh server version 2.0.2 (running on Tornado 6.1)
2021-07-28 18:40:25,087 User authentication hooks NOT provided (default user enabled)
2021-07-28 18:40:25,092 Bokeh app running at: http://localhost:5006/
2021-07-28 18:40:25,092 Starting Bokeh server with process id: 26668
2021-07-28 18:40:28:KCWI:INFO: proc table file not found: kcwi.proc
2021-07-28 18:40:28:DRPF:INFO: Framework initialized
2021-07-28 18:40:28:DRPF:WARNING: KB*.fits is not a file
Traceback (most recent call last):
  File "c:\users\mcken\.conda\envs\kcwidrp\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mcken\.conda\envs\kcwidrp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mcken\.conda\envs\kcwidrp\Scripts\reduce_kcwi.exe\__main__.py", line 7, in <module>
  File "c:\users\mcken\.conda\envs\kcwidrp\lib\site-packages\kcwidrp\scripts\reduce_kcwi.py", line 243, in main
    focus_frames = data_set.data_table[data_set.data_table.OBJECT ==
  File "c:\users\mcken\.conda\envs\kcwidrp\lib\site-packages\pandas\core\generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'OBJECT'

**Comment by MNBrod** [comment]
Am I correct in assuming that you are using Windows? If that's the case, unfortunately there isn't much help I can offer: WMKO doesn't install or run any scientific software on non-unix systems, so we are unable to replicate the issue. It was an oversight on our end to not put that in the documentation in a clear spot (we'll be fixing that ASAP). Apologies for that.
